# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: shaohua's blog
subtitle: ''
description: ''
keywords:
author: shaohua
language: zh-CN
timezone: ''



# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-xoxo

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repository: git@github.com:zshlovely/zshlovely.github.io.git
  branch: master
