
# html lang
language: zh-CN

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  #categories: /categories
  search: /search
  about: https://zshlovely.github.io/
  #rss: https://github.com/fenghuayangyi

# Miscelaneous
favicon: images/logo.png

search:
  path: search.xml
  field: post

#RSS feed https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content_limit: 140

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js
sitemap:
    path: sitemap.xml

disqus_shortname: Fenghuayangyi

google_analytics: Fenghuayangyi
baidu_analytics: Fenghuayangyi

show_excerpt: true
show_date: true

#footer
index_page: https://zshlovely.github.io/
main_site: https://zshlovely.github.io/
github: https://github.com/fenghuayangyi
